holdings: 10.00

maxholdings: -1

prefix: Fe

topsize: 5

currency:
  negative: false
  major:
    single: Fe
    multiple: Fe
  minor:
    enabled: false
    single: Fe
    multiple: Fe
  prefix: ""

type: sqlite

autoclean: true

cacheaccounts: true